[project]
name = "dash-project"
version = "0.1.0"
description = "Interactive Dashboards with Dash"
requires-python = ">=3.8"
dependencies = [
    "dash>=2.14.0",
    "dash-bootstrap-components>=1.4.0",
    "plotly",
    "pandas",
    "nbformat>=5.10.4",
]
